export const SET_ALERTA = 'SET_ALERTA';
export const REMOVE_ALERTA ='REMOVE_ALERTA';
export const CADASTRO_SUCESSO ='CADASTRO_SUCESSO';
export const CADASTRO_FALHA ='CADASTRO_FALHA';
export const USUARIO_CARREGADO ='USUARIO_CARREGADO';
export const ERRO_AUTENTICACAO ='ERRO_AUTENTICACAO';
export const LOGIN_SUCESSO ='LOGIN_SUCESSO';
export const LOGIN_FALHA ='LOGIN_FALHA';
export const PEGA_PERFIL ='PEGA_PERFIL';
export const ERRO_PERFIL ='ERRO_PERFIL';
export const LOGOUT ='LOGOUT';
export const CLEAR_PERFIL ='CLEAR_PERFIL'; //limpa do local storage
export const ATUALIZA_PERFIL ='ATUALIZA_PERFIL';
export const CONTA_DELETADA ='CONTA_DELETADA';
export const PEGA_PERFIS ='PEGA_PERFIS';
export const PEGA_GITHUB ='PEGA_GITHUB';

export const PEGA_SABER ='PEGA_SABER';
export const PEGA_SABERES ='PEGA_SABERES';
export const ERRO_SABER ='ERRO_SABER';
export const ATUALIZA_CURTIDAS ='ATUALIZA_CURTIDAS';
export const ATUALIZA_INSCRIÇÃO ='ATUALIZA_INSCRIÇÃO';

export const DELETA_SABER = 'DELETA_SABER'
export const ADICIONA_SABER = 'ADICIONA_SABER'
export const ADICIONA_COMENTARIO = 'ADICIONA_COMENTARIO'
export const DELETA_COMENTARIO = 'DELETA_COMENTARIO'
